### ISSUE TITLE
Process for Adding New Apps?

### ISSUE THREAD

**Issue by benyanke** [portainer/templates#85]
This is a really great idea, and I'm working on adding more useful apps in this format, so they can be spun up very easily.

What is your current process for adding applications? I've currently put them all in one PR (#84), but if there is a preferred process, I can follow that.

Also, I'm aware the images are all not in ideal locations, or are too large, etc. Once the PR is finalized and approved, I will go copy and resize all images to be properly sized and centralized.

Lastly, if you're looking for additional contributors, I'd be more than willing to add any useful applications I find to this repo. If that's not what you're looking for here, I can run my own as well. Just looking for thoughts on this to get on the same page.

**Comment by deviantony** [comment]
Hi @benyanke 

Thanks for contributing, currently the process for adding new apps is that we determine (with @ncresswell) which template should be added inside our official app templates list.

Once we decide which template should be added, an issue is generally created inside this repository to add the template to our feed.

You might want to join us on Slack in order to help us decide which template should be added, I'm going to close both this issue and #84 (as there is just too many templates addition).

Feel free to re-open/comment if you miss some information.
